Channel request
chxru/hospe pull request #23
Opened 2022-07-07 21:50 UTC by narangodaNPP

add crud operation for channeling

2022-07-07 22:17 UTC, chxru requested changes

2022-07-07 22:17 UTC, chxru commented on apps/api/.gitignore
> +.env
Move .env config to root dir

2022-07-07 22:17 UTC, chxru commented on apps/api/src/app/app.module.ts
> +require('dotenv').config();
Use nestjs's config module
https://docs.nestjs.com/techniques/configuration

2022-07-07 22:17 UTC, chxru commented on apps/api/src/app/channeling/channeling.controller.ts
> +  Patch,
Unused import

2022-07-07 22:17 UTC, chxru commented on apps/api/src/app/app.module.ts
> +import { MongooseModule } from '@nestjs/mongoose';
Package is missing in package.json

2022-07-07 22:17 UTC, chxru commented on apps/api/src/app/channeling/channeling.module.ts
> +import { MongooseModule } from '@nestjs/mongoose';
Package is missing in package.json

2022-07-07 22:17 UTC, chxru commented on apps/api/src/app/channeling/channeling.service.ts
> +import { UpdateChannelingDto } from './dto/update-channeling.dto';
Unused import

2022-07-07 22:17 UTC, chxru commented on apps/api/src/app/channeling/channeling.service.ts
> +import { Model } from 'mongoose';
Package is missing in package.json

2022-07-07 22:17 UTC, chxru commented on apps/api/src/app/channeling/entities/channeling.entity.ts
> +import * as mongoose from 'mongoose';
Package is missing in package.json

2022-07-07 22:52 UTC, narangodaNPP commented on apps/api/.gitignore
> +.env
moved to root dir

2022-07-07 23:05 UTC, narangodaNPP commented on apps/api/src/app/app.module.ts
> +import { MongooseModule } from '@nestjs/mongoose';
added missing package

2022-07-07 23:07 UTC, narangodapasan commented on apps/api/src/app/app.module.ts
> +require('dotenv').config();
changed the code structure, check this

2022-07-07 23:33 UTC, narangodaNPP commented on apps/api/src/app/channeling/channeling.service.ts
> +import { Model } from 'mongoose';
mongoose package added

2022-07-07 23:34 UTC, narangodapasan commented on apps/api/src/app/channeling/channeling.service.ts
> +import { UpdateChannelingDto } from './dto/update-channeling.dto';
removed import

2022-07-07 23:35 UTC, narangodaNPP commented on apps/api/src/app/channeling/channeling.controller.ts
> +  Patch,
removed unused import

2022-07-08 12:50 UTC, chxru requested changes
package-lock.json should not exists. Use yarn for all dependency installs

2022-07-08 17:13 UTC, chxru requested changes

2022-07-08 17:13 UTC, chxru commented on apps/api/src/app/channeling/channeling.service.ts
> +import { UpdateChannelingDto } from './dto/update-channeling.dto';
@narangodaNPP UpdateChannelingDto is still unused

2022-07-09 07:54 UTC, chxru approved these changes

2022-07-09 07:55 UTC, merged